name: Deploy Github pages

on:
  push:
    branches:
      - master

permissions:
    contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Update next.config.ts with basePath
        run: |
          sed -i "s|basePath: '.*'$|basePath: '/CyberOchmistrz'|g" next.config.ts |
          cat next.config.ts
      - name: Update manifest.webmanifest with basePath
        run: |
          sed -i 's|"start_url": "/|"start_url": "/CyberOchmistrz/|g' public/manifest.webmanifest
          sed -i 's|"src": "./|"src": "/CyberOchmistrz/|g' public/manifest.webmanifest
          cat public/manifest.webmanifest
      - name: Build
        run: npm run build
      - name: Add .nojekyll file
        run: touch out/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: out
